dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.1
  - OpenZeppelin/openzeppelin-contracts@4.9.1
compiler:
  solc:
    remappings:
      - '@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: ganache-local